/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/LOyl5Wee15h
 */

'use client';

import { useChat } from 'ai/react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { AvatarImage, AvatarFallback, Avatar } from '@/components/ui/avatar';

export function Chat() {
	const { messages, input, handleInputChange, handleSubmit } = useChat();
	return (
		<div key="1" className="flex h-screen bg-white dark:bg-zinc-800">
			<section className="flex flex-col w-full">
				<header className="border-b dark:border-zinc-700 p-4">
					<h2 className="text-xl font-bold flex items-center gap-2">
						<Avatar className="relative overflow-visible w-10 h-10">
							<AvatarImage alt="User Avatar" src="/placeholder-avatar.jpg" />
							<AvatarFallback>🤖</AvatarFallback>
						</Avatar>
						<div>My Assistant</div>
					</h2>
				</header>
				<main className="flex-1 overflow-auto p-4">
					<div className="space-y-8">
						{messages.map((m) => (
							<div
								className={`flex items-end gap-2 ${
									m.role === 'user' ? '' : 'justify-end'
								}`}
								key={m.id}
							>
								<div
									className={`max-w-96 ${
										m.role === 'user'
											? 'bg-zinc-200 dark:bg-zinc-700'
											: 'bg-blue-500 text-white'
									} whitespace-pre-wrap rounded-lg p-2`}
								>
									<p className="text-sm">
										<span className="text-lg">
											{m.role === 'user' ? '😊 ' : '🤖 '}
										</span>
										{m.content}
									</p>
								</div>
							</div>
						))}
					</div>
				</main>
				<footer className="border-t dark:border-zinc-700 p-4">
					<form className="flex items-center gap-2" onSubmit={handleSubmit}>
						<Input
							className="flex-1"
							placeholder="Type a message..."
							value={input}
							onChange={handleInputChange}
						/>
						<Button type="submit">Send</Button>
					</form>
				</footer>
			</section>
		</div>
	);
}
